[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"
  # Remove these lines - we'll set them only in the Netlify UI
  # TINA_CLIENT_ID = "${TINA_CLIENT_ID}"
  # TINA_TOKEN = "${TINA_TOKEN}"